# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-template-tongyx361',
                'doc_host': 'https://tongyx361.github.io',
                'git_url': 'https://github.com/tongyx361/nbdev-template-tongyx361',
                'lib_path': 'pkg_name'},
  'syms': {'pkg_name.core': {'pkg_name.core.foo': ('core.html#foo', 'pkg_name/core.py')}}}
